name: CI

on:
  push:
    branches: [main, shivam,frontend]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx tsc --noEmit
      - run: npm run test
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}